### ISSUE TITLE
Not compatible with rails 5.1.0

### ISSUE THREAD

**Issue by vonchristian** [minnowlab/simple-line-icons-rails#7]
When I updated rails version to '5.1.0' this error comes up:
simple-line-icons-rails was resolved to 0.0.1, which depends on
      railties (< 5.0, >= 3.2)

**Comment by JeskTop** [comment]
https://github.com/minnowlab/simple-line-icons-rails/commit/dd023c6a3ec91de16542857f2503d09032eb6958
This commit already fix for `5.1.0`, maybe you can update `simple-line-icons-rails` to `0.1.2`.

**Comment by vonchristian** [comment]
Thanks. It works.
