### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by cimtico** [minnowlab/simple-line-icons-rails#8]
Would it be possible to get rails 5 support for this?

**Comment by ubugnu** [comment]
user https://github.com/codeponpon/simple-line-icons-rails for 5.2 support

**Comment by leogiertz** [comment]
@ubugnu Could you do a PR with your tiny change back to this repo and then maybe @JeskTop could merge and create a new release? Would be 🎈

**Comment by JeskTop** [comment]
@ubugnu create a PR, I will merge and create a new release. Thanks.

**Comment by leogiertz** [comment]
@JeskTop I made one: https://github.com/minnowlab/simple-line-icons-rails/pull/9

**Comment by arvidjanson** [comment]
@JeskTop Any chance of getting #9 merged soon? Thanks!

**Comment by JeskTop** [comment]
@arvidjanson Done!
